server:
  port: 8080
spring:
  application:
    name: marketplace-api
  mongodb:
#    uri: mongodb://root:verysecret@mongo:27017/gobots?authSource=admin
    uri: mongodb://root:verysecret@localhost:27017/gobots?authSource=admin
  threads:
    virtual:
      enabled: true